title: Erika Granada
description: Documentation, UX, and copy writing portfolio.
theme: just-the-docs

url: https://erikagranada.github.io/portfolio

# Configuration

# Images
favicon_ico: "/assets/images/logo.png"

# Search
search_enabled: true

# Diagrams
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Links

# External navigation
nav_external_links:
  - title: CV
    url: https://drive.google.com/file/d/1i7kB3XiHvR0diQ2OeI_oL2uvqSSkhncu/view?usp=drive_link
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
    nav_order: 4
  - title: View MkDocs site
    url: 
    opens_in_new_tab: true
    nav_order: 5
  - title: View Docusaurus site
    opens_in_new_tab: true
    nav_order: 6

# Heading anchor links
heading_anchors: true

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: grey-lt